### ISSUE TITLE
Soul Daggers and Void Tendrils don't damage Pure Vessel

### ISSUE THREAD

**Issue by Blackest-Winter** [Samihamer1/Hollow-Knight-ExtraSpells#2]
I ran into an issue, where in 9 out of 10 cases the Soul Daggers won't register any hit on Pure Vessel and Sealed Vessel, and Void Tendrils don't damage them at all. And Shade Summon will only appear for a brief moment and disappear without doing anything.

**Comment by Samihamer1** [comment]
just pushed out an update that should fix the vessels not taking damage - shade summon works as intended, it just spawns in a shade enemy from the void. if the player doesn't have voidheart it'll attack, otherwise it'll just disappear.
